</section>
		<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2>&#10132;&#10132;&#10132;</h2>
							<p>Hãy tìm tới chúng tôi...</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<iframe width="152" height="77" src="//www.youtube.com/embed/0RU0BypeDJY?list=UU1Rm6atZWk3U6QgsLruXt9w" frameborder="0" allowfullscreen></iframe>
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>Facebook</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<div class="iframe-img">
									<iframe width="152" height="77" src="//www.youtube.com/embed/0RU0BypeDJY?list=UU1Rm6atZWk3U6QgsLruXt9w" frameborder="0" allowfullscreen></iframe>
								</div>
								<a href="#">
								<p>Circle of Hands</p>
								<h2>Youtube</h2>
								</a>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="<?php echo BASE_URL ?>public/maylocnuoc/images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>Google+</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="<?php echo BASE_URL ?>public/maylocnuoc/images/home/iframe4.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>Twitter</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="<?php echo BASE_URL ?>public/maylocnuoc/images/home/map.png" alt="" />
							<p>Nguyễn Đức Thuận - Trâu Quỳ - Gia Lâm - Hà Nội(Lối vào KĐT Đặng Xá).</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Giới thiệu</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Về đại lý máy lọc nước</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Hướng dẫn chung</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Hướng dẫn mua hàng</a></li>
								<li><a href="#">Hình thức thanh toán</a></li>
								<li><a href="#">Chính sách bảo hành</a></li>
								<li><a href="#">Chính sách đổi, trả lại hàng và hoàn tiền</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Sản phẩm & dịch vụ</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#"></a></li>
								<li><a href="#"></a></li>
								<li><a href="#"></a></li>
								<li><a href="#"></a></li>
								<li><a href="#"></a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Thông tin liên hệ</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Website: www.dailymaylocnuoc.com</a></li>
								<li><a href="#">Email: tranvanson1982@gmail.com</a></li>
								<li><a href="#">Hotline: 0904 501 820</a></li>
								<li><a href="#">Địa chỉ: Số 00 Nguyễn Đức Thuận - Trâu Quỳ - Gia Lâm - Hà Nội</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About We</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2014 dailymaylocnuoc.com. All rights reserved.</p>
					<p class="pull-right"><span><a target="_blank" href="#">Designed by JosT 0986 749 132 &nbsp;&nbsp;&nbsp;&nbsp;</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
	

  
    <script src="<?php echo BASE_URL ?>public/maylocnuoc/js/jquery.js"></script>
	<script src="<?php echo BASE_URL ?>public/maylocnuoc/js/bootstrap.min.js"></script>
	<script src="<?php echo BASE_URL ?>public/maylocnuoc/js/jquery.scrollUp.min.js"></script>
	<script src="<?php echo BASE_URL ?>public/maylocnuoc/js/price-range.js"></script>
    <script src="<?php echo BASE_URL ?>public/maylocnuoc/js/jquery.prettyPhoto.js"></script>
    <script src="<?php echo BASE_URL ?>public/maylocnuoc/js/main.js"></script>
    <!-- Tooltip js -->
    <script src="<?php echo BASE_URL ?>public/maylocnuoc/js/tooltip.js"></script>
    <script>
    $(document).ready(function(){
    	$('.item').eq(0).addClass('active');
    });
    </script>
    <!-- Tooltip -->
    <script src="js/tooltip.js"></script>
     <script type="text/javascript">
	     $(document).ready(function(){
	         $(".tooltip").simpletooltip();
	     });
     </script>
</body>
</html>