<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?php echo $data['title'] ?></title>
    <link href="<?php echo BASE_URL ?>public/maylocnuoc/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo BASE_URL ?>public/maylocnuoc/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?php echo BASE_URL ?>public/maylocnuoc/css/prettyPhoto.css" rel="stylesheet">
    <link href="<?php echo BASE_URL ?>public/maylocnuoc/css/price-range.css" rel="stylesheet">
    <link href="<?php echo BASE_URL ?>public/maylocnuoc/css/animate.css" rel="stylesheet">
	<link href="<?php echo BASE_URL ?>public/maylocnuoc/css/main.css" rel="stylesheet">
    <link href="<?php echo BASE_URL ?>public/maylocnuoc/css/responsive.css" rel="stylesheet">
    <!-- Tooltip css -->
	<link href="<?php echo BASE_URL ?>public/maylocnuoc/css/tooltip.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="<?php echo BASE_URL ?>public/maylocnuoc/images/ico/avatar.ico">
</head><!--/head-->