		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Máy lọc nước</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#gd">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Máy lọc nước gia đình
										</a>
									</h4>
								</div>
								<div id="gd" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="#">5 cấp lọc</a></li>
											<li><a href="#">6 cấp lọc</a></li>
											<li><a href="#">7 cấp lọc</a></li>
											<li><a href="#">8 cấp lọc</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#vp">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Máy lọc nước bán công nghiệp
										</a>
									</h4>
								</div>
								<div id="vp" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="#">Fendi</a></li>
											<li><a href="#">Guess</a></li>
											<li><a href="#">Valentino</a></li>
											<li><a href="#">Dior</a></li>
											<li><a href="#">Versace</a></li>
											<li><a href="#">Armani</a></li>
											<li><a href="#">Prada</a></li>
											<li><a href="#">Dolce and Gabbana</a></li>
											<li><a href="#">Chanel</a></li>
											<li><a href="#">Gucci</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#csl">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Máy lọc nước công suất lớn
										</a>
									</h4>
								</div>
								<div id="csl" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="#">Nike </a></li>
											<li><a href="#">Under Armour </a></li>
											<li><a href="#">Adidas </a></li>
											<li><a href="#">Puma</a></li>
											<li><a href="#">ASICS </a></li>
										</ul>
									</div>
								</div>
							</div>
							
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#lln">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Lõi lọc nước
										</a>
									</h4>
								</div>
								<div id="lln" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="#">Lõi lọc 1</a></li>
											<li><a href="#">Lõi lọc 2</a></li>
											<li><a href="#">Lõi lọc 3</a></li>
											<li><a href="#">Lõi lọc 4</a></li>
											<li><a href="#">Lõi lọc 5</a></li>
											<li><a href="#">Khác</a></li>
										</ul>
									</div>
								</div>
							</div>
							
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#dv">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Dịch vụ
										</a>
									</h4>
								</div>
								<div id="dv" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="#">Lắp đặt</a></li>
											<li><a href="#">Sửa chữa</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Phụ tùng, linh kiện</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					
						<div class="brands_products"><!--brands_products-->
							<h2>Nhãn hiệu</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#"> <span class="pull-right">(50)</span>Karofi</a></li>
									<li><a href="#"> <span class="pull-right">(56)</span>Kangaroo</a></li>
									<li><a href="#"> <span class="pull-right">(27)</span>Ohido</a></li>
									<li><a href="#"> <span class="pull-right">(32)</span>Kashuko</a></li>
									<li><a href="#"> <span class="pull-right">(5)</span>Oddmolly</a></li>
									<li><a href="#"> <span class="pull-right">(9)</span>Boudestijn</a></li>
									<li><a href="#"> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->
						
						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->
					
					</div>
				</div>