<?php 
    setTemplate('admin/head');
    setTemplate('admin/header');
    setTemplate('admin/left');
 ?>
 <style>
    label{
        float: left;
        width: 150px;
    }
    input {
        width: 400px;
        margin-bottom: 10px;
    }
    .error{
        color: red;
        font-style: italic;
    }
 </style>
<!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Form Edit
                        <small>Slider Show</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>admin/home"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/slider">Slider Show</a></li>
                        <li class="active">Edit</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-6">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Slider Show Edit</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" action="" method="post" enctype="multipart/form-data">
                                    <div class="box-body">
                                    <?php
										if($slider = $this->slider): 
                                     ?>
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input type="name" name="name" value="<?php echo $slider['name'] ?>" placeholder="Enter category name">
                                            <span class="error"><?php echo isset($this->errorName) ? $this->errorName : ""; ?></span>
                                            <br>
                                            <label for="">Title</label>
                                        	<input type="text" name="title" value="<?php echo $slider['title'] ?>" placeholder="Enter title">
                                            <span class="error"><?php echo isset($this->errorTitle) ? $this->errorTitle : ""; ?></span>
                                            <br>
                                            <label for="">Status</label>
                                            <select name="status" id="">
                                                <option value="1" <?php if($slider['status'] == 1){ echo "selected = 'selected'";} ?>>Show</option>
                                                <option value="2" <?php if($slider['status'] == 2){ echo "selected = 'selected'";} ?>>Hidden</option>
                                            </select>
                                            <br>
                                            <br>
                                            <label for="">Images</label>
                                            <input type="file" name="image" value="">
                                            <span class="error"><?php echo @$this->errorImage ?></span>
                                            <br>
                                            <?php 
                                                if($slider['images']){
                                                	$folder = $slider['id'];
                                                    echo '<label for="">&nbsp;</label>';
                                                    echo '<img src="'.BASE_URL.'uploads/slider/'.$folder.'/'.$slider['images'].'" alt="'.$slider['images'].'" width="300">';
                                                    echo "<br>";
                                                }
                                             ?>
                                        </div>
                                    	<label for="">Description</label>
                                    	<br>
                                    	<br>
	                                        <textarea name="description" class="textarea" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"><?php echo $slider['description'] ?></textarea>
                                    		<br>
                                    		<p class="error"><?php echo @$this->errorDescription ?></p>
                                        <label>Rewrite</label>
                                        <br>
                                        <br>
                                        <textarea name="rewrite" class="ckeditor" id="editor" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"><?php echo $slider['rewrite'] ?></textarea> 
                                        <br>
                                    	<p class="error"><?php echo @$this->errorRewrite ?></p>
                                    </div> 
                                	<?php endif; ?>
                                    <div class="box-footer">
                                        <button type="submit" class="btn btn-primary" name="update">Update</button>
                                    </div>
                                </form>
                            </div><!-- /.box -->
                        </div><!--/.col (right) -->
                    </div>   <!-- /.row -->
                </section><!-- /.content -->
            </aside><!-- /.right-side -->

<?php setTemplate('admin/footer') ?>