<?php 
  setTemplate('admin/head');
  setTemplate('admin/header');
  setTemplate('admin/left');
 ?>

    <form action="<?php echo BASE_URL ?>admin/slider/delete" method="post">
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">                
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Slider Show Tables
                        <small>list slider show</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>admin/home"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/slider">Slider Show</a></li>
                        <li class="active">Slider Show tables</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Data Tables </h3>                                    
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                              <th><input type="checkbox"></th>
                                                <th style="text-align:center; width:5% ">Images</th>
                                                <th style="text-align:center">Name</th>
                                                <th style="text-align:center">Title</th>
                                                <th style="text-align:center;width: 5%">Status</th>
                                                <th style="text-align:center">Description</th>
                                                <th style="text-align:center">Rewrite</th>
                                                <th style="text-align:center; width:9%">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                          if($this->slider):
                                            foreach ($this->slider as $valueSlider):
                                                $folder = $valueSlider['id'];
                                                if($valueSlider['images']){
                                                $img = '<img src="'.BASE_URL.'uploads/slider/'.$folder.'/'.$valueSlider['images'].'" alt="'.$valueSlider['images'].'" width="30">';
                                                } else {
                                                    $img = '<img src="'.BASE_URL.'uploads/no_image.jpg" alt="no image" width="30">';
                                                }
                                         ?>
                                            <tr>
                                                <td><input type="checkbox" name="id[]" value="<?php echo $valueSlider['id'] ?>"></td>
                                                <td><?php echo $img; ?></td>
                                                <td><?php echo $valueSlider['name'] ?></td>
                                                <td><?php echo $valueSlider['title'] ?></td>
                                                <?php 
                                                  if($valueSlider['status'] == 1){
                                                    echo "<td style='text-align:center;'>Show</td>";
                                                  } elseif($valueSlider['status'] == 2){
                                                    echo "<td style='text-align:center;'>Hidden</td>";
                                                  }
                                                 ?>
                                                <td><?php echo $valueSlider['description'] ?></td>
                                                <td><?php echo $valueSlider['rewrite'] ?></td>
                                                <td>
                                                  <a href="<?php echo BASE_URL."admin/slider/edit/".$valueSlider['id'] ?>" class="btn btn-primary">Edit</a>
                                                  <button class="btn btn-danger">Delete</button>

                                                </td>
                                            </tr>
                                        <?php 
                                            endforeach;
                                          endif;
                                         ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                              <th style="width:2%"></th>
                                                <th style="text-align:center; width:5% ">Images</th>
                                                <th style="text-align:center">Name</th>
                                                <th style="text-align:center">Title</th>
                                                <th style="text-align:center">Status</th>
                                                <th style="text-align:center">Description</th>
                                                <th style="text-align:center">Rewrite</th>
                                                <th style="text-align:center">
                                                  <a href="<?php echo BASE_URL ?>admin/slider/insert" class="btn btn-primary">Insert</a>
                                                </th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>

                </section><!-- /.content -->
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
    </form>


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo BASE_URL ?>public/admin/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- DATA TABES SCRIPT -->
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo BASE_URL ?>public/admin/js/AdminLTE/app.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
        </script>

    </body>
</html>