<?php 
    if ($this->product) {
        $product = $this->product;
    }
    setTemplate('admin/head');
    setTemplate('admin/header');
    setTemplate('admin/left');
 ?>
 <style>
    label{
        float: left;
        width: 125px;
    }
    .error{
        color: red;
        font-style: italic;
    }
 </style>
<form action="" method="post" enctype="multipart/form-data">
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Form Edit
                        <small>Product</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/product">Product</a></li>
                        <li class="active">Edit</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-md-6">

                            <div class="box box-info">
                                <div class="box-header">
                                    <h3 class="box-title">Thông tin chung</h3>
                                </div>
                                <div class="box-body">
                                    <div class="form-group">
                                        <label>Model</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-barcode"></i>
                                            </div>
                                            <input type="text" name="name" class="form-control pull-right" value="<?php echo $product['pro_name'] ?>"/>
                                        </div><!-- /.input group -->
                                        <?php 
                                            if (@$this->errorName) {
                                                echo '<p class="error">'.$this->errorName.'</p>';
                                            }
                                         ?>
                                    </div><!-- /.form group -->
                                    <div class="form-group">
                                        <label>Price</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-dollar"></i>
                                            </div>
                                            <input type="text" class="form-control pull-right" name="price" value="<?php echo $product['pro_price'] ?>"/>
                                        </div><!-- /.input group -->
                                        <?php 
                                            if (@$this->errorPrice) {
                                                echo '<p class="error">'.$this->errorPrice.'</p>';
                                            }
                                         ?>
                                    </div><!-- /.form group -->
                                    <div class="form-group">
                                        <label>Trạng thái</label>
                                        <div class="input-group">
                                            <select name="status">
                                                <option value="1"<?php if ($product['pro_status'] == 1) {
                                                    echo "selected = 'selected'";
                                                } ?>>Hiển thị</option>
                                                <option value="2"<?php if ($product['pro_status'] == 2) {
                                                    echo "selected = 'selected'";
                                                } ?>>Không hiển thị</option>
                                            </select>
                                        </div><!-- /.input group -->
                                    </div><!-- /.form group -->
                                    <label for="">Thông tin mô tả</label>
                                    <br>
                                    <br>
                                        <textarea name="information" class="ckeditor" placeholder="Thông tin mô tả sản phẩm" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"><?php echo $product['pro_information'] ?></textarea>
                                        <br>
                                        <p class="error"><?php echo @$this->errorInformation ?></p>
                                    <label>Bài viết</label>
                                    <br>
                                    <br>
                                    <textarea name="rewrite" class="ckeditor" id="editor" placeholder="Bài viết cho sản phẩm" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"><?php echo $product['pro_rewrite'] ?></textarea> 
                                    <br>
                                    <p class="error"><?php echo @$this->errorRewrite ?></p>

                                </div><!-- /.box-body -->
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary" name="insert">Update</button>
                                </div>
                            </div><!-- /.box -->


                        </div><!-- /.col (left) -->
                        <div class="col-md-6">
                            <div class="box box-info">
                                <div class="box-header">
                                    <h3 class="box-title">Thông tin SEO</h3>
                                </div>
                                <div class="box-body">
                                    <div class="form-group">
                                        <label>Title</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-flag-o"></i>
                                            </div>
                                            <input type="text" class="form-control pull-right" name="title" value="<?php echo $product['pro_title'] ?>" placeholder="Enter title"/>
                                        </div><!-- /.input group -->
                                        <?php 
                                            if (@$this->errorTitle) {
                                                echo '<p class="error">'.$this->errorTitle.'</p>';
                                            }
                                         ?>
                                    </div><!-- /.form group -->
                                    <div class="form-group">
                                        <label>Url Rewrite</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-bookmark-o"></i>
                                            </div>
                                            <input type="text" class="form-control pull-right" name="url_rewrite" value="<?php echo $product['pro_url_rewrite'] ?>" placeholder="Enter url rewrite"/>
                                        </div><!-- /.input group -->
                                        <?php 
                                            if (@$this->errorUrl) {
                                                echo '<p class="error">'.$this->errorUrl.'</p>';
                                            }
                                         ?>
                                    </div><!-- /.form group -->
                                    <!-- textarea -->
                                    <div class="form-group">
                                        <label>Meta keyword</label>
                                            <textarea name="keyword" class="form-control" rows="3" placeholder="Enter meta keyword"><?php echo $product['pro_meta_keyword'] ?></textarea>
                                        <?php 
                                            if (@$this->errorKeyword) {
                                                echo '<p class="error">'.$this->errorKeyword.'</p>';
                                            }
                                         ?>
                                    </div>
                                    <div class="form-group">
                                        <label>Meta description</label>
                                            <textarea name="meta_description" class="form-control" rows="3" placeholder="Enter meta description"><?php echo $product['pro_meta_description'] ?></textarea>
                                        <?php 
                                            if (@$this->errorMetaDescription) {
                                                echo '<p class="error">'.$this->errorMetaDescription.'</p>';
                                            }
                                         ?>
                                    </div>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Danh mục sản phẩm</h3>
                                </div>
                                <div class="box-body">
                                    <!-- checkbox -->
                                    <div class="form-group">
                                    <?php 
                                        if (@$this->category) {
                                            foreach ($this->category as $value) {
                                                $checked = "";
                                                if ($this->catePro) {
                                                    $catePro = $this->catePro;
                                                    foreach ($catePro as $valueCatePro) {
                                                        if ($valueCatePro['cate_id'] == $value['cate_id']) {
                                                            $checked = "checked = 'checked'";
                                                        }
                                                    }
                                                }
                                                echo '<input type="checkbox" name="category[]" value="'.$value['cate_id'].'"'.$checked.'> '.$value['cate_name'].'<br>';
                                            }
                                        }
                                     ?>
                                    </div>

                                </div><!-- /.box-body -->
                            </div><!-- /.box -->

                            <!-- iCheck -->
                            <div class="box box-success">
                                <div class="box-header">
                                    <h3 class="box-title">Ảnh sản phẩm</h3>
                                </div>
                                <div class="box-body"
                                    <br>
                                    <div class="form-group">
                                        <label>Ảnh đại diện</label>
                                        <div class="input-group">
                                            <input type="file" name="image" value=""/>
                                        </div><!-- /.input group -->
                                        <?php 
                                            if ($product['pro_image']) {
                                                echo '<img src="'.BASE_URL.'uploads/products/'.$product['pro_id'].'/'.$product['pro_image'].'" alt="'.$product['pro_image'].'" width="100">';
                                            }
                                         ?>
                                    </div><!-- /.form group -->
                                    <div class="form-group">
                                        <label>Ảnh sản phẩm</label>
                                        <div class="input-group">
                                            <input type="file" name="images[]" multiple="multiple"/>
                                        </div><!-- /.input group -->
                                        <?php 
                                            if ($this->image) {
                                                foreach ($this->image as $key => $value) {
                                                    echo '<img src="'.BASE_URL.'uploads/products/images/'.$product['pro_id'].'/'.$value['image'].'" alt="'.$value['image'].'" width="100">';
                                                }
                                            }
                                         ?>
                                    </div><!-- /.form group -->
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div><!-- /.col (right) -->
                    </div><!-- /.row -->                    

                </section><!-- /.content -->
            </aside><!-- /.right-side -->
</form>
<?php setTemplate('admin/footer') ?>