<?php 
  setTemplate('admin/head');
  setTemplate('admin/header');
  setTemplate('admin/left');
 ?>

    <form action="<?php echo BASE_URL ?>admin/product/delete" method="post">
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">                
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Products Tables
                        <small>list products</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>admin/home"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/product">Products</a></li>
                        <li class="active">Products tables</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Data Tables </h3>                                    
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th><input type="checkbox"></th>
                                                <th style="text-align:center; width:10% ">Ảnh đại diện</th>
                                                <th style="text-align:center;">Tên sản phẩm</th>
                                                <th style="text-align:center;width: 10%">Giá</th>
                                                <th style="text-align:center;width: 10%">Tình trạng</th>
                                                <th style="text-align:center">Ngày tạo</th>
                                                <th style="text-align:center">Ngày sửa</th>
                                                <th style="text-align:center; width:8%"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                          if($this->product):
                                            foreach ($this->product as $valuePro):
                                              if($valuePro['pro_image']){
                                                $img = '<img src="'.BASE_URL.'uploads/products/'.$valuePro['pro_id'].'/'.$valuePro['pro_image'].'" alt="'.$valuePro['pro_image'].'" width="100">';
                                              } else {
                                                $img = '<img src="'.BASE_URL.'uploads/no_image.jpg" alt="no image" width="100">';
                                              }
                                         ?>
                                            <tr>
                                                <td style="text-align:center;vertical-align: middle;"><input type="checkbox" name="id[]" value="<?php echo $valuePro['pro_id'] ?>"></td>
                                                <td style="text-align:center;vertical-align: middle;"><?php echo $img; ?></td>
                                                <td style="text-align:center;vertical-align: middle;"><?php echo $valuePro['pro_name'] ?></td>
                                                <td style="text-align:center;vertical-align: middle;"><?php echo $valuePro['pro_price'] ?></td>
                                                <?php 
                                                  if($valuePro['pro_status'] == 1){
                                                    echo "<td style='text-align:center;vertical-align: middle;'>Hiển thị</td>";
                                                  } elseif($valuePro['pro_status'] == 2){
                                                    echo "<td style='text-align:center;vertical-align: middle;'>Không hiện thị</td>";
                                                  }
                                                 ?>
                                                <td style="text-align:center;vertical-align: middle;"><?php echo $valuePro['pro_create_date'] ?></td>
                                                <td style="text-align:center;vertical-align: middle;"><?php echo $valuePro['pro_update_date'] ?></td>
                                                <td style="text-align:center;vertical-align: middle;">
                                                    <a href="<?php echo BASE_URL."admin/product/edit/".$valuePro['pro_id'] ?>" class="btn btn-primary">Sửa</a>
                                                    <input type="submit" class="btn btn-danger" value="Xóa">

                                                </td>
                                            </tr>
                                        <?php 
                                            endforeach;
                                          endif;
                                         ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                              <th style="width:2%"></th>
                                                <th style="text-align:center;">Ảnh đại diện</th>
                                                <th style="text-align:center">Tên sản phẩm</th>
                                                <th style="text-align:center;">Giá</th>
                                                <th style="text-align:center">Tình trạng</th>
                                                <th style="text-align:center">Ngày tạo</th>
                                                <th style="text-align:center">Ngày sửa</th>
                                                <th style="text-align:center">
                                                  <a href="<?php echo BASE_URL ?>admin/product/insert" class="btn btn-primary">Insert</a>
                                                </th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>

                </section><!-- /.content -->
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
    </form>


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo BASE_URL ?>public/admin/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- DATA TABES SCRIPT -->
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo BASE_URL ?>public/admin/js/AdminLTE/app.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
        </script>

    </body>
</html>