<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>Đại lý máy lọc nước | Đăng nhập | Đăng ký</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="<?php echo ADMIN_PATH ?>css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="<?php echo ADMIN_PATH ?>css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="<?php echo ADMIN_PATH ?>css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->      
        <link rel="shortcut icon" href="<?php echo BASE_URL ?>public/maylocnuoc/images/ico/avatar.ico">
    </head>
    <body class="bg-black">

        <div class="form-box" id="login-box">
            <div class="header">Sign In</div>
            <form action="" method="post">
                <div class="body bg-gray">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" placeholder="User ID" value="<?php echo isset($_POST['name']) ? $_POST['name'] : "" ?>" />
                        <p style="margin-top: 10px; font-style:italic; color: red; text-align:center;">
	                        <?php echo isset($this->errorName) ? $this->errorName : ""; ?>
	                    </p>
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Password" value="<?php echo isset($_POST['password']) ? $_POST['password'] : "" ?>" />
                        <p style="margin-top: 10px; font-style:italic; color: red; text-align:center;">
	                        <?php echo isset($this->errorPassword) ? $this->errorPassword : ""; ?>
	                    </p>
                    </div>          
                    <div class="form-group">
                        <input type="checkbox" name="remember_me"/> Remember me
                    </div>
                </div>
                <div class="footer">                                                               
                    <button type="submit" class="btn bg-olive btn-block">Login</button>
                    <p style="margin-top: 10px; font-style:italic; color: red; text-align:center;">
                        <?php echo isset($this->errorLogin) ? $this->errorLogin : ""; ?>
                    </p>  
            </form>
        </div>


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo ADMIN_PATH ?>js/bootstrap.min.js" type="text/javascript"></script>        

    </body>
</html>