<?php 
	setTemplate('admin/head');
	setTemplate('admin/header');
	setTemplate('admin/left');
 ?>


            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">                
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        User Tables
                        <small>list users</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>admin/home"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/user">Users</a></li>
                        <li class="active">User tables</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Data Tables </h3>                                    
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                            	<th><input type="checkbox"></th>
                                                <th style="text-align:center; width:5% ">Images</th>
                                                <th style="text-align:center">Name</th>
                                                <th style="text-align:center">Email</th>
                                                <th style="text-align:center">Address</th>
                                                <th style="text-align:center">Lever</th>
                                                <th style="text-align:center; width:9%">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                        	if($this->user):
                                        		foreach ($this->user as $valueUser):
                                         ?>
                                            <tr>
                                                <td><input type="checkbox" name="id[]" value="<?php echo $valueUser['id'] ?>"></td>
                                                <td><img src="<?php echo BASE_URL ?>uploads/no_image.jpg" alt="" width="30"></td>
                                                <td><?php echo $valueUser['name'] ?></td>
                                                <td><?php echo $valueUser['email'] ?></td>
                                                <td><?php echo $valueUser['address'] ?></td>
                                                <?php 
                                                	if($valueUser['lever'] == 1){
                                                		echo "<td>Administrator</td>";
                                                	} else {
                                                		echo "<td>Member</td>";
                                                	}
                                                 ?>
                                                <td>
                                                	<a href="" class="btn btn-primary">Edit</a>
                                                	<a href="" class="btn btn-danger">Delete</a>

                                                </td>
                                            </tr>
                                        <?php 
                                        		endforeach;
                                        	endif;
                                         ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                            	<th style="width:2%"><input type="checkbox"></th>
                                                <th style="text-align:center">Images</th>
                                                <th style="text-align:center">Name</th>
                                                <th style="text-align:center">Email</th>
                                                <th style="text-align:center">Address</th>
                                                <th style="text-align:center">Lever</th>
                                                <th style="text-align:center">
                                                	<a href="<?php echo BASE_URL ?>admin/user/insert" class="btn btn-primary">Insert</a>
                                                </th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>

                </section><!-- /.content -->
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo BASE_URL ?>public/admin/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- DATA TABES SCRIPT -->
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo BASE_URL ?>public/admin/js/AdminLTE/app.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
        </script>

    </body>
</html>