<?php 
	setTemplate('admin/head');
	setTemplate('admin/header');
	setTemplate('admin/left');
 ?>

        <form action="<?php echo BASE_URL ?>admin/image/delete" method="post">
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">                
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Image Tables
                        <small>list image</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>admin/home"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/image">Image</a></li>
                        <li class="active">Image tables</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Data Tables </h3>                                    
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                            	<th style="width:2%"><input type="checkbox"></th>
                                                <th style="text-align:center;width:3%">Number</th>
                                                <th style="text-align:center">Name</th>
                                                <th style="text-align:center">Product</th>
                                                <th style="text-align:center; width:5%">Status</th>
                                                <th style="text-align:center; width:9%">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php 
                                        	$number = 1;
                                        	if($this->class):
                                        		foreach ($this->class as $valueClass):
                                         ?>
                                            <tr>
                                                <td><input type="checkbox" name="id[]" value="<?php echo $valueClass['class_id'] ?>"></td>
                                                <td style="text-align:center"><?php echo $number; ?></td>
                                                <td><?php echo $valueClass['class_name'] ?></td></td>
                                                <td><?php echo $valueClass['class_rewrite'] ?></td></td>
                                                <?php 
                                                    if($valueClass['class_status'] == 1){
                                                        echo "<td style='text-align:center'>Show</td>";
                                                    } elseif($valueClass['class_status'] == 2) {
                                                        echo "<td style='text-align:center'>Hidden</td>";
                                                    }
                                                 ?>
                                                <td>
                                                	<a href="<?php echo BASE_URL."admin/class/edit/".$valueClass['class_id'] ?>" class="btn btn-primary">Edit</a>
                                                    <input type="submit" class="btn btn-danger" value="Delete">

                                                </td>
                                            </tr>
                                        <?php 
                                        		$number++;
                                        		endforeach;
                                        	endif;
                                         ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                            	<th></th>
                                                <th style="text-align:center">Number</th>
                                                <th style="text-align:center">Name</th>
                                                <th style="text-align:center">Rewrite</th>
                                                <th style="text-align:center">Status</th>
                                                <th style="text-align:center">
                                                	<a href="<?php echo BASE_URL ?>admin/image/insert" class="btn btn-primary">Insert</a>
                                                </th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>

                </section><!-- /.content -->
            </aside><!-- /.right-side -->
        </form>
        </div><!-- ./wrapper -->

        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo BASE_URL ?>public/admin/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- DATA TABES SCRIPT -->
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="<?php echo BASE_URL ?>public/admin/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo BASE_URL ?>public/admin/js/AdminLTE/app.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
        </script>

    </body>
</html>