<?php 
    setTemplate('admin/head');
    setTemplate('admin/header');
    setTemplate('admin/left');
 ?>
 <style>
    label{
        float: left;
        width: 150px;
    }
    input {
        width: 400px;
        margin-bottom: 10px;
    }
    .error{
        color: red;
        font-style: italic;
    }
 </style>
<!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Form Edit
                        <small>Categories</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo BASE_URL ?>admin/home"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="<?php echo BASE_URL ?>admin/category">Categories</a></li>
                        <li class="active">Edit</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Categories Edit</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                                <form role="form" action="" method="post">
                                    <div class="box-body">
                                        <div class="form-group">
                                        <?php 
                                        	$category = $this->infoCategory;
                                         ?>
                                            <label>Name</label>
                                            <input type="name" name="name" value="<?php echo $category['cate_name'] ?>" placeholder="Enter category name">
                                            <span class="error"><?php echo isset($this->errorCateName) ? $this->errorCateName : ""; ?></span>
                                            <br>
                                            <label for="">Title</label>
                                        	<input type="text" name="title" value="<?php echo $category['cate_title'] ?>" placeholder="Enter title">
                                            <span class="error"><?php echo isset($this->errorCateTitle) ? $this->errorCateTitle : ""; ?></span>
                                            <br>
                                            <label for="">Meta Keyword</label>
                                        	<input type="text" name="keyword" value="<?php echo $category['cate_metakeyword'] ?>" placeholder="Enter meta keyword">
                                            <span class="error"><?php echo isset($this->errorCateKeyword) ? $this->errorCateKeyword : ""; ?></span>
                                            <br>
                                            <label for="">Status</label>
                                            <select name="status" id="">
                                                <option value="1"<?php if($category['cate_status'] == 1){ echo "selected='selected'"; } ?>>Show</option>
                                                <option value="2"<?php if($category['cate_status'] == 2){ echo "selected='selected'"; } ?>>Hidden</option>
                                            </select>
                                            <br>
                                        </div>
                                            <label>Rewrite</label>
                                        <br>
                                        <br>
                                        <textarea name="rewrite" class="ckeditor" id="editor" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"><?php echo $category['cate_rewrite'] ?></textarea> 
                                        <br>
                                        <p class="error"><?php echo @$this->errorCateRewrite ?></p>
                                    </div> 
                                    <div class="box-footer">
                                        <button type="submit" class="btn btn-primary" name="update">Update</button>
                                    </div>
                                </form>
                            </div><!-- /.box -->
                        </div><!--/.col (right) -->
                    </div>   <!-- /.row -->
                </section><!-- /.content -->
            </aside><!-- /.right-side -->

<?php setTemplate('admin/footer') ?>